export enum ROLES {
    SUPER_ADMINISTRATOR = 'SUPER ADMINISTRATOR',
    ADMINISTRATOR = 'ADMINISTRATOR',
    OPERATOR = 'OPERATOR',
    SECRETARY = 'SECRETARY',
    BASIC = 'BASIC'
}

export enum ACCESS_LEVEL {
    DEVELOPER = 30,
    MANTEINER = 40,
    OWNER = 50
}