export enum CONFIG {
    PORT_APLICATION = 'PORT_APLICATION',
    PORT = 'PORT',
    HOST = 'HOST',
    USER_NAME = 'USER_NAME',
    PASSWORD = 'PASSWORD',
    DATABASE = 'DATABASE',
    JWT_SECRET = 'JWT_SECRET',
    DEFAULT_USER_USERNAME = 'DEFAULT_USER_USERNAME',
    DEFAULT_USER_PASSWORD = 'DEFAULT_USER_PASSWORD',
  }